# coding: utf-8

"""
Codesphere Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from codesphere_sdk.api.domains_api import DomainsApi


class TestDomainsApi(unittest.IsolatedAsyncioTestCase):
    """DomainsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DomainsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_domains_create_domain(self) -> None:
        """Test case for domains_create_domain

        createDomain
        """
        pass

    async def test_domains_delete_domain(self) -> None:
        """Test case for domains_delete_domain

        deleteDomain
        """
        pass

    async def test_domains_get_domain(self) -> None:
        """Test case for domains_get_domain

        getDomain
        """
        pass

    async def test_domains_list_domains(self) -> None:
        """Test case for domains_list_domains

        listDomains
        """
        pass

    async def test_domains_update_domain(self) -> None:
        """Test case for domains_update_domain

        updateDomain
        """
        pass

    async def test_domains_update_workspace_connections(self) -> None:
        """Test case for domains_update_workspace_connections

        updateWorkspaceConnections
        """
        pass

    async def test_domains_verify_domain(self) -> None:
        """Test case for domains_verify_domain

        verifyDomain
        """
        pass


if __name__ == "__main__":
    unittest.main()
