# coding: utf-8

"""
Codesphere Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from codesphere_sdk.models.workspaces_get_workspace_status200_response import (
    WorkspacesGetWorkspaceStatus200Response,
)


class TestWorkspacesGetWorkspaceStatus200Response(unittest.TestCase):
    """WorkspacesGetWorkspaceStatus200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> WorkspacesGetWorkspaceStatus200Response:
        """Test WorkspacesGetWorkspaceStatus200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `WorkspacesGetWorkspaceStatus200Response`
        """
        model = WorkspacesGetWorkspaceStatus200Response()
        if include_optional:
            return WorkspacesGetWorkspaceStatus200Response(
                is_running = True
            )
        else:
            return WorkspacesGetWorkspaceStatus200Response(
                is_running = True,
        )
        """

    def testWorkspacesGetWorkspaceStatus200Response(self):
        """Test WorkspacesGetWorkspaceStatus200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
