# coding: utf-8

"""
Codesphere Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from codesphere_sdk.models.teams_get_team200_response import TeamsGetTeam200Response


class TestTeamsGetTeam200Response(unittest.TestCase):
    """TeamsGetTeam200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamsGetTeam200Response:
        """Test TeamsGetTeam200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TeamsGetTeam200Response`
        """
        model = TeamsGetTeam200Response()
        if include_optional:
            return TeamsGetTeam200Response(
                id = 0,
                default_data_center_id = 0,
                name = '',
                description = '',
                avatar_id = '',
                avatar_url = '',
                is_first = True
            )
        else:
            return TeamsGetTeam200Response(
                id = 0,
                default_data_center_id = 0,
                name = '',
        )
        """

    def testTeamsGetTeam200Response(self):
        """Test TeamsGetTeam200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
