# coding: utf-8

"""
Codesphere Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from codesphere_sdk.models.workspaces_create_workspace_request import (
    WorkspacesCreateWorkspaceRequest,
)


class TestWorkspacesCreateWorkspaceRequest(unittest.TestCase):
    """WorkspacesCreateWorkspaceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspacesCreateWorkspaceRequest:
        """Test WorkspacesCreateWorkspaceRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `WorkspacesCreateWorkspaceRequest`
        """
        model = WorkspacesCreateWorkspaceRequest()
        if include_optional:
            return WorkspacesCreateWorkspaceRequest(
                team_id = 0,
                name = '',
                plan_id = 0,
                is_private_repo = True,
                replicas = 1,
                base_image = '',
                git_url = '',
                initial_branch = '',
                clone_depth = 1,
                source_workspace_id = 0,
                welcome_message = '',
                vpn_config = ''
            )
        else:
            return WorkspacesCreateWorkspaceRequest(
                team_id = 0,
                name = '',
                plan_id = 0,
                is_private_repo = True,
                replicas = 1,
        )
        """

    def testWorkspacesCreateWorkspaceRequest(self):
        """Test WorkspacesCreateWorkspaceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
