# coding: utf-8

"""
Codesphere Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from codesphere_sdk.models.workspaces_server_logs200_response import (
    WorkspacesServerLogs200Response,
)


class TestWorkspacesServerLogs200Response(unittest.TestCase):
    """WorkspacesServerLogs200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspacesServerLogs200Response:
        """Test WorkspacesServerLogs200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `WorkspacesServerLogs200Response`
        """
        model = WorkspacesServerLogs200Response()
        if include_optional:
            return WorkspacesServerLogs200Response(
                data = codesphere_sdk.models._problem_data._problem_data(
                    status = 100,
                    title = '',
                    detail = '',
                    trace_id = '', ),
                event = 'problem'
            )
        else:
            return WorkspacesServerLogs200Response(
                data = codesphere_sdk.models._problem_data._problem_data(
                    status = 100,
                    title = '',
                    detail = '',
                    trace_id = '', ),
                event = 'problem',
        )
        """

    def testWorkspacesServerLogs200Response(self):
        """Test WorkspacesServerLogs200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
