# coding: utf-8

"""
Codesphere Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from codesphere_sdk.models.problem_data import ProblemData


class TestProblemData(unittest.TestCase):
    """ProblemData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProblemData:
        """Test ProblemData
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ProblemData`
        """
        model = ProblemData()
        if include_optional:
            return ProblemData(
                status = 100,
                title = '',
                detail = '',
                trace_id = ''
            )
        else:
            return ProblemData(
                status = 100,
                title = '',
                trace_id = '',
        )
        """

    def testProblemData(self):
        """Test ProblemData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
