# coding: utf-8

"""
Codesphere Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from codesphere_sdk.models.domains_get_domain200_response_custom_config import (
    DomainsGetDomain200ResponseCustomConfig,
)


class TestDomainsGetDomain200ResponseCustomConfig(unittest.TestCase):
    """DomainsGetDomain200ResponseCustomConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> DomainsGetDomain200ResponseCustomConfig:
        """Test DomainsGetDomain200ResponseCustomConfig
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DomainsGetDomain200ResponseCustomConfig`
        """
        model = DomainsGetDomain200ResponseCustomConfig()
        if include_optional:
            return DomainsGetDomain200ResponseCustomConfig(
                max_body_size_mb = 1.337,
                max_connection_timeout_s = 1.337,
                use_regex = True,
                restricted = True
            )
        else:
            return DomainsGetDomain200ResponseCustomConfig(
        )
        """

    def testDomainsGetDomain200ResponseCustomConfig(self):
        """Test DomainsGetDomain200ResponseCustomConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
