# coding: utf-8

"""
Codesphere Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from codesphere_sdk.models.domains_get_domain200_response_domain_verification_status import (
    DomainsGetDomain200ResponseDomainVerificationStatus,
)


class TestDomainsGetDomain200ResponseDomainVerificationStatus(unittest.TestCase):
    """DomainsGetDomain200ResponseDomainVerificationStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> DomainsGetDomain200ResponseDomainVerificationStatus:
        """Test DomainsGetDomain200ResponseDomainVerificationStatus
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DomainsGetDomain200ResponseDomainVerificationStatus`
        """
        model = DomainsGetDomain200ResponseDomainVerificationStatus()
        if include_optional:
            return DomainsGetDomain200ResponseDomainVerificationStatus(
                verified = True,
                reason = ''
            )
        else:
            return DomainsGetDomain200ResponseDomainVerificationStatus(
                verified = True,
                reason = '',
        )
        """

    def testDomainsGetDomain200ResponseDomainVerificationStatus(self):
        """Test DomainsGetDomain200ResponseDomainVerificationStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
