# coding: utf-8

"""
Codesphere Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from codesphere_sdk.api.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.IsolatedAsyncioTestCase):
    """WorkspacesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = WorkspacesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_workspaces_create_workspace(self) -> None:
        """Test case for workspaces_create_workspace

        createWorkspace
        """
        pass

    async def test_workspaces_delete_env_var(self) -> None:
        """Test case for workspaces_delete_env_var

        deleteEnvVar
        """
        pass

    async def test_workspaces_delete_workspace(self) -> None:
        """Test case for workspaces_delete_workspace

        deleteWorkspace
        """
        pass

    async def test_workspaces_deploy_landscape(self) -> None:
        """Test case for workspaces_deploy_landscape

        deployLandscape
        """
        pass

    async def test_workspaces_deploy_landscape1(self) -> None:
        """Test case for workspaces_deploy_landscape1

        deployLandscape
        """
        pass

    async def test_workspaces_execute_command(self) -> None:
        """Test case for workspaces_execute_command

        executeCommand
        """
        pass

    async def test_workspaces_get_workspace(self) -> None:
        """Test case for workspaces_get_workspace

        getWorkspace
        """
        pass

    async def test_workspaces_get_workspace_status(self) -> None:
        """Test case for workspaces_get_workspace_status

        getWorkspaceStatus
        """
        pass

    async def test_workspaces_git_head(self) -> None:
        """Test case for workspaces_git_head

        gitHead
        """
        pass

    async def test_workspaces_git_pull(self) -> None:
        """Test case for workspaces_git_pull

        gitPull
        """
        pass

    async def test_workspaces_git_pull1(self) -> None:
        """Test case for workspaces_git_pull1

        gitPull
        """
        pass

    async def test_workspaces_git_pull2(self) -> None:
        """Test case for workspaces_git_pull2

        gitPull
        """
        pass

    async def test_workspaces_list_env_vars(self) -> None:
        """Test case for workspaces_list_env_vars

        listEnvVars
        """
        pass

    async def test_workspaces_list_workspaces(self) -> None:
        """Test case for workspaces_list_workspaces

        listWorkspaces
        """
        pass

    async def test_workspaces_logs(self) -> None:
        """Test case for workspaces_logs

        logs
        """
        pass

    async def test_workspaces_pipeline_status(self) -> None:
        """Test case for workspaces_pipeline_status

        pipelineStatus
        """
        pass

    async def test_workspaces_replica_logs(self) -> None:
        """Test case for workspaces_replica_logs

        replicaLogs
        """
        pass

    async def test_workspaces_server_logs(self) -> None:
        """Test case for workspaces_server_logs

        serverLogs
        """
        pass

    async def test_workspaces_set_env_var(self) -> None:
        """Test case for workspaces_set_env_var

        setEnvVar
        """
        pass

    async def test_workspaces_start_pipeline_stage(self) -> None:
        """Test case for workspaces_start_pipeline_stage

        startPipelineStage
        """
        pass

    async def test_workspaces_start_pipeline_stage1(self) -> None:
        """Test case for workspaces_start_pipeline_stage1

        startPipelineStage
        """
        pass

    async def test_workspaces_stop_pipeline_stage(self) -> None:
        """Test case for workspaces_stop_pipeline_stage

        stopPipelineStage
        """
        pass

    async def test_workspaces_teardown_landscape(self) -> None:
        """Test case for workspaces_teardown_landscape

        teardownLandscape
        """
        pass

    async def test_workspaces_update_workspace(self) -> None:
        """Test case for workspaces_update_workspace

        updateWorkspace
        """
        pass


if __name__ == "__main__":
    unittest.main()
